version: '3.9'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./compose/dev/django/Dockerfile
  #   command: /start
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 9000:9000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - 5432:5432

volumes:
  postgres_data: