# Generated by Django 4.0.6 on 2022-07-31 08:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=32, default=Decimal('0'), editable=False, max_digits=64),
        ),
    ]
