# Generated by Django 4.0.6 on 2022-07-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('success', 'Success')], default='pending', editable=False, max_length=255),
        ),
    ]
